- name: Start checkpointz
  hosts: checkpointz
  gather_facts: true
  serial: 20
  tasks:
    - name: Start checkpointz 
      docker_container:
        name: "{{ checkpointz_container_name }}"
        state: started
        image: "{{ checkpointz_image_name }}"
        pull: true
        restart_policy: unless-stopped
        network_mode: bridge
        ports: 
          - "{{ checkpointz_http_listen_port }}:5555"
        restart: "{{ checkpointz_require_restart | default(false) }}"
        command: "{{ checkpointz_start_args }}"
        volumes: "{{ checkpointz_volumes }}"
