el_client_name: ethereumjs
el_image_name: g11tech/ethereumjs:latest
execution_endpoint: http://127.0.0.1:{{el_engine_snoop_port}}
snoop_command: "./json_rpc_snoop -p {{el_engine_snoop_port}} http://127.0.0.1:{{el_engine_port}}"

home_dir: "/home/{{ansible_user}}"

el_github_external_user_pubkeys:
  - g11tech
  - acolytec3
  - holgerd77
  - jochem-brouwer 

el_volumes:
  - "{{el_node_dir}}:/eldata"
  - "{{testnet_dir}}:/networkdata"
  - "{{home_dir}}/jwtsecret:/jwtsecret"

el_env:
  DEBUG: vm:*

el_start_args: >
  --dataDir=/eldata
  --gethGenesis=/networkdata/genesis.json
  --rpc --rpcPort={{el_rpc_port}} --rpcAddr=0.0.0.0 --rpcCors="*"
  --rpcEngine --rpcEnginePort={{el_engine_port}} --rpcEngineAddr=0.0.0.0
  --jwtSecret=/jwtsecret
  --extIP={{ansible_host}}
  --maxPeers=75
  {% if (el_bootnode_enode is defined) and el_bootnode_enode %}
  --bootnodes="{{ el_bootnode_enode | join(',') }}"
  {% endif %}
  --ws --wsPort={{el_ws_rpc_port}} --wsAddr=0.0.0.0 --wsEnginePort=8552
  --logLevel=debug

el_user_id: "1000:1000"