##############################################
# generic ansible config information
##############################################
ansible_user: "devops"
bootstrap_user: "devops"
initial_remote_user: "root"

github_user_pubkeys:
  - parithosh
  - barnabasbusa
  - skylenet
  - samcm
  - savid
  - infosecual
  

ansible_python_interpreter: /usr/bin/python3
oh_my_zsh_config:
  PROMPT: "%{$fg[yellow]%}%n%{$fg[white]%}@%{$fg[red]%}%m%{$reset_color%} ${PROMPT}"

##############################################
# el endpoints
##############################################
# nimbus requires a websocket endpoint (http support unstable)
# note: also used for execution engine endpoint in nimbus
consensus_endpoint_nimbus: ws://127.0.0.1:8551
beacon_api_endpoint: "http://127.0.0.1:{{beacon_api_port}}"
elendpoint: http://127.0.0.1:8545

# Merge Engine endpoints
# TODO change IP?
# TODO: some engines might start using the 8550 port (or 8551 for ws)

##############################################
# testnet specific information
##############################################
testnet_type: custom
cl_network_name: withdrawal-devnet-7
chainID: 1337811
fee_recipient: "0xf97e180c050e5Ab072211Ad2C213Eb5AEE4DF134"
upload_bls_keys: true
# enter bootnodes here if needed
bootnode_enrs:
  - "enr:-Iq4QMCTfIMXnow27baRUb35Q8iiFHSIDBJh6hQM5Axohhf4b6Kr_cOCu0htQ5WvVqKvFgY28893DHAg8gnBAXsAVqmGAX53x8JggmlkgnY0gmlwhLKAlv6Jc2VjcDI1NmsxoQK6S-Cii_KmfFdUJL2TANL3ksaKUnNXvTCv1tLwXs0QgIN1ZHCCIyk"
  - "enr:-Ly4QOejdqJ68ZgSnUPsQ5ZMe7Y_VEISwRtre51wwd8t_3k-KGxSO14pXg0AIAjm_eibAZxgyMkzELIaite46pM_sxwBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpAEF12pQAAARMIBAAAAAAAAgmlkgnY0gmlwhK6KBJ6Jc2VjcDI1NmsxoQPdgGhtl1f7T0w1AhtgkVhH3ihMa0-4pH6TKWegTPtM0ohzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA"
  - "enr:-LK4QAt2AUgoo1UQFU0C8Co7_unFGvRAp7PQTfZapSAn7jh0DjmM8TuzxciVSKMUH3Zfog8Nyp6LqvIHltDZsunbNs4Bh2F0dG5ldHOIAAAAAAAAAACEZXRoMpAEF12pQAAARMIBAAAAAAAAgmlkgnY0gmlwhLymEqKJc2VjcDI1NmsxoQK68v3jFuy4TDm9SLSnw_9iOd2__EMUXsdI5apiD0z1h4N0Y3CCIyiDdWRwgiMo"
  - "enr:-MK4QKNvAE1Tc8-DxqIjCanNk59yHeLOsH3E5gldBKm-1qBsZtkgVuyTvFcfKI7cWMz3Oiaa191abHPui6Ou3QxMDLmGAYZLIejsh2F0dG5ldHOIAAAAAAAAAACEZXRoMpAEF12pQAAARMIBAAAAAAAAgmlkgnY0gmlwhIDHLuWJc2VjcDI1NmsxoQJ-hrl5b0PhvXxEXphLJf1jqiYbltzF2ZtUV5QZOnWVIYhzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA"
  - "enr:-KG4QI5f7qm8T4ou31uelCjh6TyWtiN3WrSlP-wJBDii-yotdIA1l242ObvGOgHjVPZMZuiqERNXKQ5No8pty1FO2P0DhGV0aDKQBBddqUAAAETCAQAAAAAAAIJpZIJ2NIJpcISuigmeiXNlY3AyNTZrMaEDgVOhu6jIgeq5dAAhtWw5Uq5sfNR5dnZpY5J2d1hapmiDdGNwgiMog3VkcIIjKA"
  - "enr:-MS4QKtgWWQnxYOvkhFmWe5pTdv6MvLTcZwJT_tN_QrTn0_rL4hVFWUa4zcyKojUiF_1rvhzKuGBl65Cu-w9EYvRRlgHh2F0dG5ldHOIAAAAAAAAAACEZXRoMpAEF12pQAAARMIBAAAAAAAAgmlkgnY0gmlwhM69Zf6Jc2VjcDI1NmsxoQOR0BirIqBAkIPYmZJSn_c_QS9rqOJ4l3lore28pVDD2ohzeW5jbmV0c4gAAAAAAAAAAIN0Y3CCIyiDdWRwgiMo"
multiaddrs: 
  - "/ip4/174.138.4.158/tcp/9000/p2p/16Uiu2HAmTZe1ubNqQ74jxEpqQwY4SQWhFo6AbTCydfsJf7LkYoZs"
  - "/ip4/188.166.18.162/udp/9000/p2p/16Uiu2HAm81SiREZ9xvg2GkCAoMkHes4fN6qazRzAatbRGvrXerRk"
  - "/ip4/128.199.46.229/tcp/9000/p2p/16Uiu2HAm3waW1UaAjWAYYTR84CMkyRgGeqabafDKqFsWprYJw1sn"
  - "/ip4/174.138.9.158/tcp/9000/p2p/16Uiu2HAmMMpucmRGzVPuUWNnWmmCm24cm5eMttyu6FmweE77DxT9"
  - "/ip4/206.189.101.254/tcp/9000/p2p/16Uiu2HAmNUBWS7F3x2DxLkpFQpQkQZV5o6gUtiTv6hUaCxV7aEtq"
el_bootnode_enode:
  - "enode://7a62fa742b72275cdc7602595ee795cb7ae05901a1e0a85cf79ee56f8f7751a6a648aba75826cce888c9a00547579519c90ea9a73fa63c1e484ed47611c41f08@174.138.4.158:30303"
  - "enode://37b752864a0ec6533a7c6e92dfd6a65085ef31ef1ef594a1a90e041f472de7b39ec7ca3a599668a3b92c984f3ea4cb9c89c718491fd4acc35c9000e99e33c0ff@188.166.18.162:30303"
  - "enode://091c027bd3d5960c7dd8d231f806a6005c53057802af894f452db87729ce95a542b8d4c632b24bce3e6a68a080529bc74e05371d05f77b26d0959d5c20e45f10@128.199.46.229:30303"
  - "enode://13e770da2c9678a901ed3073080360bd1c0f9f408015adf2c923b3f61f0c21c98e1972e1aa4ed2a4c3e00153064eaa5854424feb00fce228084bacb9a4be0e9e@174.138.9.158:30303"
  - "enode://cebcec6de6b3f59085ad19733e081c782e0a2814f3bfb6d8202bec7b20bec58a57c50bdb68b6d7c75ba98be21428eabc00ef6ffb22f4e7c7b5adcba62e8e7803@206.189.101.254:30303"

el_static_enodes: "{{el_bootnode_enode}}"
##############################################
# metric information
##############################################
# enter pushgateway config if needed
prometheus_config_file: "prometheus/prometheus.yml.j2"
push_url: "https://victoriametrics.ethdevops.io/insert/0/prometheus/api/v1/write"
metrics_enabled: true
push_metrics_enabled: true
remote_write_auth: true
eth_metrics_exporter_enabled: true
cl_validator_metrics_enabled: false
eth_metrics_exporter_name: "metrics-exporter"
eth_metrics_exporter_image: "ethpandaops/ethereum-metrics-exporter:0.19.0"
remote_write_username: "{{ lookup('pipe', 'keybase fs read /keybase/team/ethereum.devops/eth2/monitoring/observability-cluster/metrics-ingress-users/withdrawal-devnet-7.json | jq .username') }}"
remote_write_password: "{{ lookup('pipe', 'keybase fs read /keybase/team/ethereum.devops/eth2/monitoring/observability-cluster/metrics-ingress-users/withdrawal-devnet-7.json | jq .password') }}"

domain: ethpandaops.io
no_validator_keys: false
ethstats_enabled: true
snapsync_enabled: false
ethstats_url: "ethstats.withdrawal-devnet-7.ethpandaops.io"
ethstats_password: "withdrawal-devnet-7"

##############################################
# mev boost configs
##############################################
mev_boost_image_name: flashbots/mev-boost:v1.4.0
mev_boost_container_name: mev_boost
mev_boost_start_args: "-genesis-fork-version 0x00 -relays http://example.io"
mev_boost: false

##############################################
# ports to configure
##############################################
el_rpc_port: 8545
el_ws_rpc_port: 8546
el_engine_port_no_auth: 8550
el_engine_port: 8551
el_engine_snoop_port: 8560
el_engine_ws_port: 8552
el_private_api_port: 9999
nimbus_rpc_port: 4009
beacon_api_port: 4000
beacon_grpc_port: 4001
beacon_metrics_port: 8000
beacon_p2p_port: 9000
validator_metrics_port: 8001
validator_rpc_port: 4002
node_exporter_web_listen_address: "127.0.0.1:9100"
prometheus_web_listen_address: "127.0.0.1:9101"
el_metrics_port: 8002
eth_metrics_exporter_port: 8003
mev_boost_port: 18550

##############################################
# Command for JSON RPC snooper
##############################################
snoop_image_name: parithoshj/json_rpc_snoop:v1.0.0-x86
snoop_container_name: snooper

##############################################
# name of the validator to display
##############################################
graffiti: "{{cl_client_name}}-{{el_client_name}}"

##############################################
# local data directories
##############################################
local_explorerdata_host_dir: "{{inventory_dir}}/../explorerdata"
local_explorerdata_host_archive: "{{inventory_dir}}/../explorerdata.tar.gz"
local_forkmondata_host_dir: "{{inventory_dir}}/../forkmondata"
local_forkmondata_host_archive: "{{inventory_dir}}/../forkmondata.tar.gz"
local_custom_config_data_host_dir: "{{inventory_dir}}/../custom_config_data"
local_custom_config_data_host_archive: "{{inventory_dir}}/../custom_config_data.tar.gz"
local_cl_config_filepath: "{{local_custom_config_data_host_dir}}/config.yaml"
# private dirs
# Validator assignments
local_validator_host_dir: "{{inventory_dir}}/../validator_prep/{{ansible_hostname}}"
local_validator_host_archive: "{{inventory_dir}}/../validator_prep/{{ansible_hostname}}.tar.gz"

##############################################
# remote host data directories
##############################################
beacon_node_dir: "{{home_dir}}/beacon"
validator_node_dir: "{{home_dir}}/validator"
testnet_dir: "{{home_dir}}/custom_config_data"
el_node_dir: "{{home_dir}}/eldata"

##############################################
# common log config
# Possible log levels:
# silent, error, warn, info (default), debug, detail
##############################################
execution_log_level: info
beacon_log_level: info
common_log_options:
  max-file: "10"
  max-size: 500m
  mode: non-blocking
  max-buffer-size: 4m
common_log_driver: json-file


##############################################
# container names
##############################################
beacon_container_name: beacon
validator_container_name: validator
execution_container_name: execution
hi_peer_count: 100
separate_validator_process_enabled: true

firewall_allowed_tcp_ports:
  - 22
  - 30303
  - 9000
  - 80
  - 443

firewall_allowed_udp_ports:
  - 30303
  - 9000
  - 53

firewall_flush_rules_and_chains: true

firewall_additional_rules:
  - "iptables -A INPUT -p tcp --dport 8545 -s 172.16.0.0/12 -j ACCEPT" #docker internal
  - "iptables -A INPUT -p tcp --dport 8546 -s 172.16.0.0/12 -j ACCEPT" #docker internal
  - "iptables -A INPUT -p tcp --dport 8545 -s 174.138.4.158 -j ACCEPT" #forkmon
  - "iptables -A INPUT -p tcp --dport 4000 -s 167.71.11.65 -j ACCEPT" #beaconchain explorer
  - "iptables -A INPUT -p tcp --dport 8545 -s 167.71.11.65 -j ACCEPT" #beaconchain explorer
  - "iptables -A INPUT -p tcp --dport 8546 -s 167.71.11.65 -j ACCEPT" #beaconchain explorer