txfuzz_container_name: tx-fuzz
txfuzz_image_name: ethpandaops/tx-fuzz:latest

rpc_url: http://localhost:8545
txfuzz_private_key: "{{ lookup('pipe', 'keybase fs read /keybase/team/ethereum.devops/withdrawals/devnet1/tx-fuzz-key') }}"
txfuzz_public_key: "0xf97e180c050e5Ab072211Ad2C213Eb5AEE4DF134"

txfuzz_start_args: "spam --no-al --seed={{chainID}} --sk={{txfuzz_private_key}} --rpc={{rpc_url}} --txcount 1"