# txfuzz_container_name: tx-fuzz
# txfuzz_image_name: ethpandaops/tx-fuzz:latest

# rpc_url: http://localhost:8545
# txfuzz_private_key: "{{ lookup('pipe', 'keybase fs read /keybase/team/ethereum.devops/withdrawals/devnet1/tx-fuzz-key') }}"
# txfuzz_public_key: "0xf97e180c050e5Ab072211Ad2C213Eb5AEE4DF134"

# txfuzz_start_args: "spam --no-al --seed={{chainID}} --sk={{txfuzz_private_key}} --rpc={{rpc_url}} --txcount 1"

txfuzz_container_name: tx-fuzz
txfuzz_image_name: kurtosistech/tx-fuzz:latest

rpc_url: http://withdrawal-devnet-7-lighthouse-geth-3.ethpandaops.io:8545/
txfuzz_private_key: "{{ lookup('pipe', 'keybase fs read /keybase/team/ethereum.devops/verkle/beverly-txfuzz-key') }}"
txfuzz_public_key: "0x9791DeD6e5D3d5Dafca71Bb7Bb2A14187D17e32E"

txfuzz_start_args: "{{rpc_url}} spam {{txfuzz_private_key}} {{txfuzz_public_key}}"