- name: Start mock relay
  hosts: mock_relay
  gather_facts: true
  serial: 20
  tasks:
    - name: Read config file
      shell: cat "{{ home_dir }}/jwtsecret"
      register: jwt_secret
    - name: Start mock relay
      docker_container:
        name: "{{ mock_relay_container_name }}"
        state: started
        image: "{{ mock_relay_image_name }}"
        pull: true
        restart_policy: unless-stopped
        network_mode: host
        restart: "{{ mev_relay_require_restart | default(false) }}"
        command: "{{ mock_relay_start_args }}"