##############################################
# generic ansible config information
##############################################
ansible_user: "devops"
bootstrap_user: "devops"
initial_remote_user: "root"

github_user_pubkeys:
  - parithosh
  - ralexstokes
  - djrtwo
  - skylenet
  - samcm
  - barnabasbusa
  - savid
  - potuz

ansible_python_interpreter: /usr/bin/python3
oh_my_zsh_config:
  PROMPT: "%{$fg[yellow]%}%n%{$fg[white]%}@%{$fg[red]%}%m%{$reset_color%} ${PROMPT}"

##############################################
# el endpoints
##############################################
# nimbus requires a websocket endpoint (http support unstable)
# note: also used for execution engine endpoint in nimbus
consensus_endpoint_nimbus: ws://127.0.0.1:8551

elendpoint: http://127.0.0.1:8545
beacon_api_endpoint: "http://127.0.0.1:{{beacon_api_port}}"


##############################################
# testnet specific information
##############################################
testnet_type: custom
cl_network_name: mainnet-shadowfork-3
deploy_mode: shadowfork
no_validator_keys: false
checkpoint_sync_url: "https://mainnet-checkpoint-sync.attestant.io/"
chainID: 1
fee_recipient: "0xf97e180c050e5Ab072211Ad2C213Eb5AEE4DF134"
upload_bls_keys: true
# enter bootnodes here if needed
bootnode_enrs:
  - "enr:-Iq4QMCTfIMXnow27baRUb35Q8iiFHSIDBJh6hQM5Axohhf4b6Kr_cOCu0htQ5WvVqKvFgY28893DHAg8gnBAXsAVqmGAX53x8JggmlkgnY0gmlwhLKAlv6Jc2VjcDI1NmsxoQK6S-Cii_KmfFdUJL2TANL3ksaKUnNXvTCv1tLwXs0QgIN1ZHCCIyk"
  - "enr:-KG4QOortwOofqaNzgWMaHh2bIzMu1I9rtuAUIMfwmw9klvDckvUNyKEVpOwdwcovD6mtIExuCZVRUZAHng_X8ja5EIDhGV0aDKQvGjKxkAAAEijAgAAAAAAAIJpZIJ2NIJpcISG0VahiXNlY3AyNTZrMaEDRYyn5q8xYPQHelasRsy1lBiMzTbWEu8B5ByAho7quWiDdGNwgiMog3VkcIIjKA"
  - "enr:-Ly4QAKruQ5OOKLtUAav_5rMnF_8UnIYJh9g0oAcEpJCIyvuIxh3sO3IZ-ipdaeXYCPunXQoNox0T7Onur5CkJidW8MIh2F0dG5ldHOI__________-EZXRoMpC8aMrGQAAASKMCAAAAAAAAgmlkgnY0gmlwhKdj0Y6Jc2VjcDI1NmsxoQOeV1yUicjDG2YGayntXlmgyZMATEmxIUsSvMrN_ot3rYhzeW5jbmV0cw-DdGNwgiMog3VkcIIjKA"
  - "enr:-L24QDzgBUOK3O6it1O8upVIptKnG_yS2IJ5E9ez_YGCcnf0aTYn-C8vbd-Ioq_IKVeUTG6K5wMo6RKpipKaHK6ibdqBhYdhdHRuZXRziAAAAAAAAAAAhGV0aDKQvGjKxkAAAEijAgAAAAAAAIJpZIJ2NIJpcISlFu8biXNlY3AyNTZrMaED34Ry39V1zXpudNN8ThDwqefZv49bMe0xtr3BSjYbzoaIc3luY25ldHMPg3RjcIIjKIN1ZHCCIyg"

el_bootnode_enode:
  - "enode://7c9e4cb5a7175822f1967671b2da02beaf9894a5deba7fd33e9844a48231af8f86e919ccb4125252d0bb8e17724e23f48e085b4e0133c9d1cfc0f0d3a1e2e082@165.22.204.22:30303"
  - "enode://9ad22971369366bfcd589f7dfe1cb308d5f1765ead81e7dad911ad0e5dbaa4b5ac4e87a6cac8e7e60524f9222e83a750ab30e0664a9d3158b8151ce735db4d0c@165.22.239.27:30303"
  - "enode://f20741af2743d83e03d30c49801b19b0103db81667cd8482a428cb1807a790f78a6ed2045ac45694e84803c94b6e8e63a4fc151f7c676cace3d38fcd94e52c57@167.99.209.68:30303"
  - "enode://4ebef8900c634a23b5c346fabc24d0def5dbc298352e2bb213eb31b89a2ba3a65da28d31f89ebcd295768b809c09da9ec85aadd37e0bff0852eaef8cf75ec7ff@157.245.75.159:30303"

##############################################
# metric information
##############################################
# enter pushgateway config if needed
prometheus_config_file: "prometheus/prometheus.yml.j2"
push_url: "https://victoriametrics.ethdevops.io/insert/0/prometheus/api/v1/write"
metrics_enabled: true
push_metrics_enabled: true
remote_write_auth: true
eth_metrics_exporter_enabled: true
cl_validator_metrics_enabled: false
eth_metrics_exporter_name: "metrics-exporter"
eth_metrics_exporter_image: "ethpandaops/ethereum-metrics-exporter:0.21.0"
remote_write_username: "{{ lookup('pipe', 'keybase fs read /keybase/team/ethereum.devops/eth2/monitoring/observability-cluster/metrics-ingress-users/shadow-mainnet-withdrawal-3.json | jq .username') }}"
remote_write_password: "{{ lookup('pipe', 'keybase fs read /keybase/team/ethereum.devops/eth2/monitoring/observability-cluster/metrics-ingress-users/shadow-mainnet-withdrawal-3.json | jq .password') }}"

ethstats_enabled: true
ethstats_url: "ethstats.withdrawal-mainnet-shadowfork-3.ethpandaops.io"
ethstats_password: "withdrawalmainnetshadowfork3"

##############################################
# mev boost configs
##############################################
mev_boost_image_name: flashbots/mev-boost:1.5.2-alpha2
mev_boost_container_name: mev_boost
mev_boost_start_args: "-genesis-fork-version=0x10000048 -request-timeout-regval 15000 -relays http://0xa869cb5a9b381f7195b5726a68f80820e7d8c57e8806c4bd1ca4b863ec01d5f5c340e0224ecbcd92edd28f01761bfcba@withdrawal-mainnet-shadowfork-3-prysm-geth-2.ethpandaops.io"
# Set to false when you want to selectively enable mev-boost
mev_boost: false

##############################################
# ports to configure
##############################################
el_rpc_port: 8545
el_ws_rpc_port: 8546
el_engine_port_no_auth: 8550
el_engine_port: 8551
el_engine_snoop_port: 8560
el_engine_ws_port: 8552
nimbus_rpc_port: 4009
beacon_api_port: 4000
beacon_grpc_port: 4001
beacon_metrics_port: 8000
beacon_p2p_port: 9000
validator_metrics_port: 8001
validator_rpc_port: 4002
node_exporter_web_listen_address: "0.0.0.0:9100"
prometheus_web_listen_address: "0.0.0.0:9101"
el_metrics_port: 8002
eth_metrics_exporter_port: 8003
mev_boost_port: 18550

##############################################
# Command for JSON RPC snooper
##############################################
snoop_image_name: parithoshj/json_rpc_snoop:v1.0.0-x86
snoop_container_name: snooper

##############################################
# name of the validator to display
##############################################
graffiti: "{{cl_client_name}}-{{el_client_name}}"

##############################################
# local data directories
##############################################
local_explorerdata_host_dir: "{{inventory_dir}}/../explorerdata"
local_explorerdata_host_archive: "{{inventory_dir}}/../explorerdata.tar.gz"
local_forkmondata_host_dir: "{{inventory_dir}}/../forkmondata"
local_forkmondata_host_archive: "{{inventory_dir}}/../forkmondata.tar.gz"
local_custom_config_data_host_dir: "{{inventory_dir}}/../custom_config_data"
local_custom_config_data_host_archive: "{{inventory_dir}}/../custom_config_data.tar.gz"
# private dirs
# Validator assignments
local_validator_host_dir: "{{inventory_dir}}/../validator_prep/{{ansible_hostname}}"
local_validator_host_archive: "{{inventory_dir}}/../validator_prep/{{ansible_hostname}}.tar.gz"

##############################################
# remote host data directories
##############################################
home_dir: "/home/{{ansible_user}}"
beacon_node_dir: "{{home_dir}}/beacon"
validator_node_dir: "{{home_dir}}/validator"
testnet_dir: "{{home_dir}}/custom_config_data"
el_node_dir: "{{home_dir}}/eldata"

##############################################
# common log config
##############################################
beacon_log_level: info
common_log_options:
  max-file: "10"
  max-size: 500m
  mode: non-blocking
  max-buffer-size: 4m
common_log_driver: json-file

##############################################
# container names
##############################################
beacon_container_name: beacon
validator_container_name: validator
execution_container_name: execution
hi_peer_count: 100
separate_validator_process_enabled: true

firewall_allowed_tcp_ports:
  - 22
  - 30303
  - 9000
  - 80
  - 443
  - 42069
  - 4000

firewall_allowed_udp_ports:
  - 30303
  - 9000
  - 80
  - 443
  - 42069

firewall_additional_rules:
  - "iptables -A INPUT -p tcp --dport 4000 -s 134.209.86.161 -j ACCEPT"
  - "iptables -A INPUT -p tcp --dport 8545 -s 134.209.86.161 -j ACCEPT"
  - "iptables -A INPUT -p tcp --dport 8546 -s 134.209.86.161 -j ACCEPT"